#!/usr/bin/env bash
# Bash script that configures a server to the above requirements
# Fixes the nginx listening port and reloads the nginx master process
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill nginx
service nginx start
