#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.
# Script should display:
# Username
# User ID
# Home directory path for the user
# Requirements:
# Must use the while loop (for and until are forbidden)
# Define the field separator as a colon (:)

IFS=':'

while read -r usr pswd uid gid uinfo hd csh
do
	echo "The user $usr is part of the $gid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pswd, more info about the user here: $uinfo"
done < /etc/passwd
